# Generated by Django 4.2.4 on 2023-08-21 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_populate_notificaion_types_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="tag",
            new_name="tags",
        ),
    ]
