# Generated by Django 4.2.4 on 2023-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tag_tweet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
