# Generated by Django 4.2.4 on 2023-09-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retweet",
            name="tweet",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="retweets", to="core.tweet"),
        ),
    ]
