from django.urls import path
from django.shortcuts import redirect
from core.presentation.views import (
    home_controller, 
    get_tweet_controller, 
    add_tweet_controller,  
    login_controller,
    logout_controller,
    registration_confirmation_controller,
    registration_controller,
    confirm_email_stub_controller,
    profile_controller,
    edit_profile_controller,
    tags_views_controller,
    top_tags_controller,
    like_tweet_controller,
    like_comment_controller,
    subscriber_controller,
    another_profile_controller,
    add_comment_controller,
    followings_controller,
    followers_controller,
    add_retweet_controller,
    delete_retweet_controller,
    delete_tweet_controller,
    delete_comment_controller,
    notification_controller,
    like_notification_controller,
    retweet_notification_controller,
    comment_notification_controller,
    edit_tweet_controller,
)


urlpatterns = [
    path("", lambda request: redirect("login")),
    path("home/", home_controller, name="home"),
    path("profile/", profile_controller, name="profile"),
    path("profile/<str:username>/", another_profile_controller, name="another-profile"),
    path("profile/edit", edit_profile_controller, name="edit-profile"),
    path("tweet/add/", add_tweet_controller, name="add-tweet"),
    path("tweet/<int:tweet_id>/", get_tweet_controller, name="get-tweet"),
    path("signup/", registration_controller, name="registration"),
    path("confirmation/", registration_confirmation_controller, name="confirm-signup"),
    path("confirm/note/", confirm_email_stub_controller, name="confirm-stub"),
    path("singnin/", login_controller, name="login"),
    path("logout/", logout_controller, name="logout"),
    path("tags/", tags_views_controller, name="tags"),
    path("populated/tags/", top_tags_controller, name="top_tags"),
    path("<int:tweet_id>/like", like_tweet_controller, name="like_tweet"),
    path("profile/<str:username>/sub/", subscriber_controller, name="subscribe-from-profile"),
    path("comment/<int:tweet_id>/", add_comment_controller, name="comment"),
    path("profile/<str:username>/followings", followings_controller, name="followings"),
    path("profile/<str:username>/followers", followers_controller, name="followers"),
    path("retweet/<int:tweet_id>/", add_retweet_controller, name="retweet"),
    path("tweet/<int:tweet_id>/delete/", delete_tweet_controller, name="delete_tweet"),
    path("tweet/<int:tweet_id>/comment/<int:comment_id>/delete/", delete_comment_controller, name="delete_comment"), 
    path("delete-retweet/<int:tweet_id>/", delete_retweet_controller, name="delete_retweet"),
    path("like_comment/<int:comment_id>/", like_comment_controller, name="like_comment"),
    path("notifications/", notification_controller, name="notifications"),
    path("create_like_notification/", like_notification_controller, name="create_like_notification"),
    path("create_retweet_notification/", retweet_notification_controller, name="create_retweet_notification"),
    path("create_comment_notification/", comment_notification_controller, name="create_comment_notification"),
    path("tweet/<int:tweet_id>/edit/", edit_tweet_controller, name="edit-tweet"),
    path("confirm-email/", registration_confirmation_controller, name="confirm-email"),
]
